config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vn/ do
    root "static_pages#home"

    get "static_pages/home"
    get "/help", to: "static_pages#help", as: "help"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users do
      resources :following, only: :index, as: "followings"
      resources :followers, only: :index, as: "followers"
    end

    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t(".subtitle"), Settings.help.link_rails %>
    <%= t ".by" %> <%= link_to t(".admin_name"), Settings.help.link_admin %>
  </small>
  <nav>
  <ul>
    <li><%= link_to t(".about"), "#" %></li>
    <li><%= link_to t(".contact"), "#" %></li>
    <li><%= link_to t(".news"), "#" %></li>
  </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".subtitle"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li>
            <%= link_to t(".users"), users_path %>
          </li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              "data-toggle": "dropdown" do %>
              <%= t ".account" %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= link_to t(".en"), locale: "en" %>
      <%= link_to t(".vi"), locale: "vn" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>